server.port=8082

eureka.client.service-url.defaultZone=http://localhost:8081/eureka/
eureka.client.fetch-registry=true

# Activer la découverte des services pour le Gateway
spring.cloud.gateway.discovery.locator.enabled=true

spring.cloud.gateway.routes[0].id=service-user-route  

spring.cloud.gateway.routes[0].uri=lb://SERVICE-USER
