server.port=8079
##enrgistre;ent sur eureka
eureka.client.service-url.defaultZone=http://localhost:8081/eureka/
eureka.client.register-with-eureka=true

#activation de la decouverte dynamique des microservices
eureka.client.fetch-registry=true
spring.cloud.gateway.discovery.locator.enabled=true