server.port=8082

##configuration de l'acces au serveur eureka
eureka.client.service-url.defaultZone=http://localhost:8081/eureka/
eureka.instance.prefer-ip=true

#activation de la decouverte de service
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
